### ISSUE TITLE
To-do

### ISSUE THREAD

**Issue by ty-fel** [DukeAML/Radio-Communication-Heatmap#1]
- [x] Write code to get elevation data
    * Could use an elevation api or DTED 0 data for now
    * [Overview of elevation data]( https://www.gislounge.com/overview-of-elevation-data/)
    * [DTED data](http://vterrain.org/Elevation/dted.html)
    * [Airmap API](https://developers.airmap.com/docs/elevation-api), lets you specify two locations and get a grid of data. Provides 1 arc second of spatial resolution, which is equivalent to DTED 2 data!
        - [x] Apply for a developer role at Airmap to get an API key. Update: Have the API key. Another Update: It works without an API key for some reason, so it isn't necessarily so far.
        - [x] Test the Airmap API key to get a grid of elevation data
    * Waiting on SIBR grant to see about higher resolution DTED data
- [ ] Write code to generate the heatmap
    - [x] Brainstorm other methods?
        * Current method is doing cross-correlation with a "U" shape, with the opening facing towards the group that the soldiers would want to communicate with
    - [x] Write pseudo code for heatmap algorithm
        * The pseudo-code for the algorithm is relatively simple, but we need to figure out how we are going to pick the kernels
        * Added a google doc in the DoD RF/Data Science Team google drive folder for the pseudo code
    * [Scipy 2d cross-correlation](https://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.correlate2d.html)
    - [x] Edit the code to return back locations that are not too close to one another
    - [ ] Create custom correlate function to change angle of kernel at each point
- [ ] Write code to interact with the frontend
    - [x] Talk with SWE team and pick a framework to use
    * Waiting for the SWE team to figure out how the plugin is going to function before deciding how to write this code
    * Potential Options:
        * [Flask](https://flask.palletsprojects.com/en/1.1.x/)
        * [Django](https://www.djangoproject.com/)
- [ ] RF Classification portion
    - [ ] Looking into the code
    - [ ] Looking into the paper
    - [ ] Thinking about how to incorporate it into the app
